_target_: src.inference.Inference
vllm_params: ${model.vllm}
sampling_params: ${model.sampling_params}
prompt: ${prompt}
options_file: ${medical_fields_file}
progress_file: ${save_folder}/progress.json