# https://github.com/vllm-project/vllm/blob/main/vllm/entrypoints/llm.py
defaults:
  - _self_ 
  - model: Llama-3-70B-Instruct
  - datasets: medical_tasks_test
  - hydra: default
  - prompt: prompt-cot
  - inference_engine: generate_until
  - merged_dataset: default

medical_fields: medical_fields_35_v2
num_samples: null 
version: v0
block_size: 5000

# Do not change
medical_fields_file: configs/medical_fields/${medical_fields}.txt
save_folder: "/gpfs/projects/bsc70/hpai/storage/data/heka/medical-fields/${model.name}_${prompt.name}_${version}"
log_level: INFO
