# https://github.com/vllm-project/vllm/blob/main/vllm/entrypoints/llm.py
defaults:
  - _self_ 
  - model: Mistral-7B-v0.1
  - datasets: medical_tasks_test
  - hydra: default
  - prompt: prompt-cot
  - inference_engine: generate_until
  - merged_dataset: default

medical_fields: medical_fields_5
num_samples: 50
version: v0
block_size: 2
# Do not change
medical_fields_file: configs/medical_fields/${medical_fields}.txt
save_folder: "/gpfs/projects/bsc20/bsc020561/medical-fields/${model.name}_${prompt.name}_${version}"
log_level: DEBUG